### ISSUE TITLE
Make sure the docs are up to date with the current API

### ISSUE THREAD

**Issue by RyanDavies19** [FloatingArrayDesign/MoorDyn#260]
Hi @sanguinariojoe, 

If you are opening up a PR soon can you make sure the docs examples are up to date with the current API (See #257, #259)?

Specifically the examples in [the drivers section](https://moordyn.readthedocs.io/en/latest/drivers.html#) and in [the initialization section](https://moordyn.readthedocs.io/en/latest/initialization.html).

I figure it'll be quicker for you to do it because you set those examples up.

**Comment by sanguinariojoe** [comment]
Regarding #259 (affecting [the initialization section](https://moordyn.readthedocs.io/en/latest/initialization.html)), the API entry is already there, on the dev branch though:

https://github.com/FloatingArrayDesign/MoorDyn/blob/dev/wrappers/python/moordyn/moordyn.py#L501

The problem is that the default MoorDyn readthedocs points towards dev, not master.

I will check the API and the docs anyway

**Comment by RyanDavies19** [comment]
@sanguinariojoe Thanks!

**Comment by sanguinariojoe** [comment]
Fixing on #262
